### ISSUE TITLE
Verify if it's possible to set a proxy to a running webdriver

### ISSUE THREAD

**Issue by mdallastella** [7bridges-eu/shelob#1]
It would be nice to be able to change proxy on the fly.

**Comment by manuel-uberti** [comment]
Apparently it's only possible to use `setProxy` from the driver options (e.g., `FirefoxOptions`) to set the proxy when the `WebDriver` is created.

```clojure
(defn proxy
  [proxy-type host port]
  (-> (Proxy.)
      (.setProxyType (Proxy$ProxyType/valueOf proxy-type))
      (.setHttpProxy (str host ":" port))))

(def driver
  (let [firefox-options (-> (FirefoxOptions.)
                            (.setHeadless true)
                            (.setProxy (proxy "MANUAL" "localhost" 8080)))]
    (FirefoxDriver. firefox-options)))
```

**Comment by mdallastella** [comment]
Possible [solution](https://stackoverflow.com/a/48816584). It's a Firefox hack... I'll check it out.

**Comment by manuel-uberti** [comment]
Yes, I've seen that, but since it's only for Firefox I didn't think it useful enough for our case.

**Comment by mdallastella** [comment]
Ok, I'll keep digging

**Comment by mdallastella** [comment]
Ok, it's not doable.
