### ISSUE TITLE
Implement logging functionalities

### ISSUE THREAD

**Issue by mdallastella** [7bridges-eu/shelob#4]
We can use `timbre` to implement logging functionalities.

**Comment by manuel-uberti** [comment]
I added `timbre` and configured a basic file appender: https://github.com/7bridges-eu/shelob/commit/8ec0f948f9fd9e83f333340398790048256dda3f

What do we log now? :)

**Comment by manuel-uberti** [comment]
Turns out it's better to let `shelob` user take care of logging and handle exceptions.

**Comment by manuel-uberti** [comment]
Note that the basic file appender needs to be configured, otherwise `shelob`'s clients will find a `shelob.log` file in the root of their projects.
